In [2]:
data = [10, 20, 90, 40, 100, 60, 70, 95, 90, 100, 115, 120, 130, 143, 158, 160, 170, 180, 190, 210]
print(data)

[10, 20, 90, 40, 100, 60, 70, 95, 90, 100, 115, 120, 130, 143, 158, 160, 170, 180, 190, 210]


In [3]:
import numpy as np
def splitSequence(seq, n_steps):

    X = []
    y = []

    for i in range(len(seq)):

        lastIndex = i + n_steps


        if lastIndex > len(seq) - 1:
            break


        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]


        X.append(seq_X)
        y.append(seq_y)
        pass

    X = np.array(X)
    y = np.array(y)

    return X,y

    pass

In [5]:
n_steps = 3
X, y = splitSequence(data, n_steps = 3)

In [7]:
print(X)

[[ 10  20  90]
 [ 20  90  40]
 [ 90  40 100]
 [ 40 100  60]
 [100  60  70]
 [ 60  70  95]
 [ 70  95  90]
 [ 95  90 100]
 [ 90 100 115]
 [100 115 120]
 [115 120 130]
 [120 130 143]
 [130 143 158]
 [143 158 160]
 [158 160 170]
 [160 170 180]
 [170 180 190]]


In [8]:
print(y)

[ 40 100  60  70  95  90 100 115 120 130 143 158 160 170 180 190 210]


In [9]:
for i in range(len(X)):
    print(X[i], y[i])

[10 20 90] 40
[20 90 40] 100
[ 90  40 100] 60
[ 40 100  60] 70
[100  60  70] 95
[60 70 95] 90
[70 95 90] 100
[ 95  90 100] 115
[ 90 100 115] 120
[100 115 120] 130
[115 120 130] 143
[120 130 143] 158
[130 143 158] 160
[143 158 160] 170
[158 160 170] 180
[160 170 180] 190
[170 180 190] 210


In [10]:
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[10]
  [20]
  [90]]

 [[20]
  [90]
  [40]]]


In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()


model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(Dropout(0.2))


model.add(LSTM(50, activation='relu', return_sequences=True))
model.add(Dropout(0.2))


model.add(LSTM(50, activation='relu'))
model.add(Dropout(0.2))


model.add(Dense(25, activation='relu'))
model.add(Dense(10, activation='relu'))


model.add(Dense(1))


model.compile(optimizer='adam', loss='mse')


model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 3, 50)               │          10,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 3, 50)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 3, 50)               │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 3, 50)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 50)                  │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 50)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 25)                  │           1,275 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             260 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 52,346 (204.48 KB)

 Trainable params: 52,346 (204.48 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.layers

[<LSTM name=lstm, built=True>,
 <Dropout name=dropout, built=True>,
 <LSTM name=lstm_1, built=True>,
 <Dropout name=dropout_1, built=True>,
 <LSTM name=lstm_2, built=True>,
 <Dropout name=dropout_2, built=True>,
 <Dense name=dense, built=True>,
 <Dense name=dense_1, built=True>,
 <Dense name=dense_2, built=True>]

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 3, 50)               │          10,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 3, 50)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 3, 50)               │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 3, 50)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 50)                  │          20,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 50)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 25)                  │           1,275 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             260 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 52,346 (204.48 KB)

 Trainable params: 52,346 (204.48 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [16]:
model.fit(X, y, epochs=250, verbose=1)

Epoch 1/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.0000e+00 - loss: 17868.4805
Epoch 2/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0000e+00 - loss: 17455.7656
Epoch 3/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.0000e+00 - loss: 15634.5107
Epoch 4/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.0000e+00 - loss: 10445.0576
Epoch 5/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.0000e+00 - loss: 1213.2363
Epoch 6/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0000e+00 - loss: 45451.8516
Epoch 7/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0000e+00 - loss: 2308.2146
Epoch 8/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0000e+00 - loss: 2353.7146
Epoch 9/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 5399.4858
Epoch 10/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0000e+00 - loss: 6621.9546
Epoch 11/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.0000e+00 - loss: 8321

In [18]:
test_data = np.array([90, 100, 110])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 90],
        [100],
        [110]]])

In [19]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 408ms/step
[[89.655785]]
